#!/usr/bin/env bash

doctype="${DOCTYPE:-MISC}"

while read -r file
do
	if gmi-upload --apikey "${APIKEY}" --file "${file}" --doctype "${doctype}"
	then
		if [[ -d "${1}/uploaded" ]]
		then
			mv "${file}" "${1}/uploaded"
		fi
	fi
done < <(find "${1}" -maxdepth 1 -type f -iname '*.PDF')
