name: Go

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get tags
      run: git fetch --tags origin
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Make
      run: make -C cmd/gmi-upload
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: putmybills-bin
        path: "{cmd/gmi-upload/gmi-upload-*-*,assets/gmi-putdir,init/*}"
